---
name: CI

on:
  push:

env:
  OUTPUT_PATH: /home/cross-compiler
  BINUTILS_VERSION: "2.40"
  GDB_VERSION: "13.2.0"
  GCC_VERSION: "13.1.0"

jobs:
  create-matrix-from-file:
    name: Read TARGETS file
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
        run: |
          json="{\"target\":["
          lines=$(cat .TARGETS)
          for line in $lines
          do
            json="$json $line,"
          done

          # Remove last "," and add closing brackets
          if [[ $json == *, ]]; then
            json="${json%?}"
          fi
          json="$json]}"
          echo $json

          # Set output
          echo "matrix=$( echo "$json" )" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-22.04
    needs: [create-matrix-from-file]

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.create-matrix-from-file.outputs.matrix)}}

    steps:
      - name: Read .env
        uses: falti/dotenv-action@v1.0.4

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: sudo sh ./build.sh -t ${{ matrix.target }} -o ${{ env.OUTPUT_PATH }} --binutils ${{ env.BINUTILS_VERSION }} --gdb ${{ env.GDB_VERSION }} --gcc ${{ env.GCC_VERSION }}
                
      - name: Update Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cross-compiler
          path: ${{ env.OUTPUT_PATH }}

          
  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: [build]
          
    steps:

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: cross-compiler
          path: ./artifact

      - name: Compress Artifact
        run: |
          cd ./artifact
          for d in *; do \
              if [ -d "$d" ]; then \
                  tar -czvf $d.tar.gz $d; \
              fi \
          done

      - name: Create Release
        uses: shogo82148/actions-create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: binutils-${{ env.BINUTILS_VERSION }}-gdb-${{ env.GDB_VERSION }}-gcc-${{ env.GCC_VERSION }}
          release_name: Release binutils-${{ env.BINUTILS_VERSION }} gdb-${{ env.GDB_VERSION }} gcc-${{ env.GCC_VERSION }}
          body: |
            Release Versions
            - Binutils: ${{ env.BINUTILS_VERSION }}
            - GDB: ${{ env.GDB_VERSION }}
            - GCC: ${{ env.GCC_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: shogo82148/actions-upload-release-asset@v1
        id: upload-release-assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifact/*.tar.gz